spring.application.name=SB2
server.servlet.context.path =/api
server.port = 8081
logging.level.com.app = info
logging.file.name = data.log
logging.file.path = c:\javasoftware\SBMay2026
spring.main.banner-mode = off