// <auto-generated />
using EFcoreDemo.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFcoreDemo.Migrations
{
    [DbContext(typeof(DBCon))]
    [Migration("20260629234656_ini")]
    partial class ini
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EFcoreDemo.Model.Department", b =>
                {
                    b.Property<int>("DepartID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DeptPeople")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("DepartID");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("EFcoreDemo.Model.Employee", b =>
                {
                    b.Property<int>("EmpID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DeptID")
                        .HasColumnType("int");

                    b.Property<string>("EmpEmail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Empname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("departmentDepartID")
                        .HasColumnType("int");

                    b.HasKey("EmpID");

                    b.HasIndex("departmentDepartID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("EFcoreDemo.Model.Employee", b =>
                {
                    b.HasOne("EFcoreDemo.Model.Department", "department")
                        .WithMany("Employees")
                        .HasForeignKey("departmentDepartID");

                    b.Navigation("department");
                });

            modelBuilder.Entity("EFcoreDemo.Model.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
